[package]
name = 'supra_holder'
version = '0.0.1'
upgrade_policy = "compatible"

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', subdir = 'aptos-move/framework/aptos-framework', rev = 'c7a2381ace10fd677ce549180a7f16001ef5c58d' }
supra_validator = { local = "../supra_validator" }

[addresses]
supra_holder = "7f07ca4fd4b1bc28a6d18348158ca39af540c9d3c703940a5843c5c4b126ebc4"
