[package]
name = "core"
version = "1.0.0"

[addresses]
supra_oracle = "0x3fa08a1592412d24550c415339d7244b315cddfcd60f36164401cc5441d1b160"


[dependencies.SupraFramework]
git = 'https://github.com/Entropy-Foundation/aptos-core.git'
subdir = 'aptos-move/framework/supra-framework'
rev = 'dev'

