[package]
name = "core"
version = "1.0.0"

[addresses]
supra_oracle = "0x5b1f641a3ba6356998373c8feeeaa8573b347f969be264964708627f02171e22"


[dependencies.SupraFramework]
git = 'https://github.com/Entropy-Foundation/aptos-core.git'
subdir = 'aptos-move/framework/supra-framework'
rev = 'dev'

