[package]
name = 'supra_validator'
version = '0.0.1'
upgrade_policy = "compatible"

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', subdir = 'aptos-move/framework/aptos-framework', rev = 'aptos-framework-v1.10.0' }
supra_utils = { local = "../supra_utils" }

[addresses]
supra_validator = "7f07ca4fd4b1bc28a6d18348158ca39af540c9d3c703940a5843c5c4b126ebc4"
