[package]
name = "supra_utils"
version = "0.0.1"
published-at = "0xed7b3916794d94ecf4cc919d1e2a8967dd70b1065865ef940b8b65d760d97fec"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.14.2" }

[addresses]
sui = "0x2"
supra_utils = "0xed7b3916794d94ecf4cc919d1e2a8967dd70b1065865ef940b8b65d760d97fec"
